### ISSUE TITLE
[Bug]: Jenkins LTS track workflow doesn't correctly identify the LTS releases from upstream

### ISSUE THREAD

**Issue by kz6fittycent** [snapcrafters/jenkins#105]
### What happened?

The workflow syntax for the LTS track wasn't able to correctly find the right LTS release.

### What should have happened?

The latest LTS release from upstream should be identified.

### Output of `snap info $snap_name`

```shell
n/a
```

### Output of `snap connections $snap_name`

```shell
n/a
```

### Output of `snap version`

```shell
`lts/stable:       2.440.3`
```

### Relevant log output

```shell
n/a
```

### Teminal output of app

```shell
n/a
```

**Comment by jnsgruk** [comment]
Fixed in #106
