### ISSUE TITLE
Default startup config file missing

### ISSUE THREAD

**Issue by codyshepherd** [snapcrafters/jenkins#13]
Jenkins docs identify `/etc/default/jenkins` as being the file that provides the default startup configuration for Jenkins, but when installed as a snap this file doesn't seem to exist (or be ingested). Making edits to this file is useful for, among other things, configuring jenkins to run behind a reverse proxy. Has this file been moved to another location? How does the jenkins snap take initialization arguments otherwise?

**Comment by syffs** [comment]
I doubt we're supposed to have the default config file available there as it's a snap.

@evandandrea @popey could you please advise how to change a basic configuration parameter (like httpPort 8080 to 9090) ?

**Comment by juan-chan** [comment]
I can't find the jenkins config file to change the default httpPort 8080 too.

**Comment by pamelus** [comment]
`/snap/bin/jenkins.config`

**Comment by kz6fittycent** [comment]
Closing this issue due to age and may not be valid anymore. No further issues noted or reported since 2020.
