### ISSUE TITLE
Failing review

### ISSUE THREAD

**Issue by evandandrea** [snapcrafters/jenkins#2]
Failing review in 073b8d5:
>package contains external symlinks: usr/lib/jvm/default-java/jre/lib/security/cacerts lint-snap-v2_external_symlinks

**Comment by Ads20000** [comment]
Where can we see this review or does this require extra privileges? I can only see 'build, failed to release' on my build.snapcraft.io dashboard...

**Comment by popey** [comment]
Now fixed
