### ISSUE TITLE
Unable to change configuration

### ISSUE THREAD

**Issue by alculete** [snapcrafters/jenkins#26]
When trying to change configuration with the command below I receive an error. I need to set it to run a different port
```
cat config.xml | sudo /snap/bin/jenkins.config
cat: config.xml: No such file or directory
```

**Comment by kz6fittycent** [comment]
It's located here: 
`cat /var/snap/jenkins/current/config.xml`

**Comment by kz6fittycent** [comment]
Closing this issue due to age. Resolution provided for record.
