### ISSUE TITLE
[Update Request] Update the Snap version of Jenkin's to 2.300

### ISSUE THREAD

**Issue by rtcms** [snapcrafters/jenkins#29]
Please update the Jenkins on the [Snap Store](https://snapcraft.io/jenkins) to the latest version 2.300 to fix some [Security Issue's](https://www.jenkins.io/security/advisory/2021-06-30/)

**Comment by diddledan** [comment]
The 2.300 version is available in the `edge` channel. It needs testing to verify that the build is functional, at which point it'll be bumped to stable.

**Comment by rtcms** [comment]
Awesome!
Can you please give me an ETA if possible?

**Comment by popey** [comment]
Latest release is now 302.

**Comment by rtcms** [comment]
@popey I still don't see the  2.300 version on latest/stable version :/
Am I missing anything?

**Comment by rtcms** [comment]
@popey I still don't see the  2.300 version on latest/stable channel  :/
Am I missing anything?

**Comment by popey** [comment]
@rtcms I no longer work on the team. You may want to raise this on the [snapcraft forum](https://forum.snapcraft.io/)

**Comment by rtcms** [comment]
@popey Thanks for the Head's Up :)
