### ISSUE TITLE
SSL Trust does not seem to work

### ISSUE THREAD

**Issue by tsal** [snapcrafters/jenkins#4]
If I want to use the github.com API, for example, the snap instance of Jenkins simply does not work - it refuses to verify the github.com SSL certificate.

I've checked outside of the snap, and trust works just fine.

**Comment by evberrypi** [comment]
Can confirm, this is still an issue

**Comment by kz6fittycent** [comment]
@tsal and @evberrypi do you mind testing the latest release of Jenkins to verify if this issue has been resolved?

**Comment by kz6fittycent** [comment]
I'm going to go ahead and close this issue since there's been no response. Feel free to test the latest releases to determine if this is still an issue.
