### ISSUE TITLE
[Enhancement]: The jenkins part should download the jenkins.war matching the snap version

### ISSUE THREAD

**Issue by ThyMYthOS** [snapcrafters/jenkins#80]
### What changes would you like?

This line always downloads the latest jenkins.war:
https://github.com/snapcrafters/jenkins/blob/b3b29c8ad47a1279a8a7fa23001ecc5dcfe1d9c4/snap/snapcraft.yaml#L55

The URL should be https://github.com/jenkinsci/jenkins/releases/download/jenkins-$SNAPCRAFT_PROJECT_VERSION/jenkins.war

**Comment by kz6fittycent** [comment]
Hi, 

Thanks for reaching out. If you'll take a look at the GitHub [action](https://github.com/snapcrafters/jenkins/blob/candidate/.github/workflows/sync-version-with-upstream.yml ) we're using, you'll see the logic in why we're doing it this way, which works quite well. 

For now, we'll keep it the way it is.
