### ISSUE TITLE
[Enhancement]: Use a snap channel to track LTS releases

### ISSUE THREAD

**Issue by ThyMYthOS** [snapcrafters/jenkins#81]
### What changes would you like?

There should be a snap channel tracking Jenkins LTS releases: https://www.jenkins.io/download/lts/

**Comment by kz6fittycent** [comment]
@ThyMYthOS - thanks for opening the issue. We're working it, and you can track the conversation [here](https://forum.snapcraft.io/t/lts-track-request-for-jenkins-snap/39984).

**Comment by kz6fittycent** [comment]
@ThyMYthOS - please check out the latest candidate release of Jenkins LTS.
`sudo snap install jenkins --channel=lts/candidate`

**Comment by jnsgruk** [comment]
I'll close this issue for now - the first revisions are now landed in `lts/stable` - thanks @kz6fittycent for your hard work on that!
