### ISSUE TITLE
[Enhancement]: Add a new snap 'jenkins-agent'

### ISSUE THREAD

**Issue by fleschutz** [snapcrafters/jenkins#86]
### What changes would you like?

This 'jenkins' snap is perfect to set up a Jenkins Controller (aka master). However, there is no 'jenkins-agent' snap yet to set up a Jenkins Agent (required to set up a build farm). I kindly request to provide the new snap.

**Comment by kz6fittycent** [comment]
Thanks for reaching out. We had an internal discussion regarding this request and at this time we need to focus more on some internal maintenance. We'll definitely keep this in mind for a future project - and perhaps as the team grows, another party within the team can take this on.
